name: Pull Request

on:
  pull_request:
    branches:
      - master

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused

    - name: Set up Go 1.17
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '1.17.x'

    - name: Figure out if running fork PR
      id: fork
      run: '["${{ secrets.DOCKER_REGISTRY_TOKEN }}" == ""] && echo "::set-output name=is_fork_pr::true" || echo "::set-output name=is_fork_pr::false"'

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      if: steps.fork.outputs.is_fork_pr == 'false'

    - name: Make tag
      run: echo "TAG_NAME=$(echo $GITHUB_REF | awk -F / '{print $3}')-${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

    - name: Build
      run: |
        make
        sha256sum bin/pam-exec-oauth2 > bin/pam-exec-oauth2.sha256

    - name: Prepare upload
      run: |
        export GITHUB_TAG_NAME=${TAG_NAME}
        mkdir -p pam-exec-oauth2/${GITHUB_TAG_NAME}/
        sudo chown -R $(id -u):$(id -g) bin
        mv bin/* pam-exec-oauth2/${GITHUB_TAG_NAME}/
      if: steps.fork.outputs.is_fork_pr == 'false'

    - name: Upload to GCS
      run: gsutil -m cp -r -p pam-exec-oauth2 gs://$GCS_BUCKET
      if: steps.fork.outputs.is_fork_pr == 'false'
