name: Release

on:
  release:
    types:
      - published

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused
    - name: Set up Go 1.17
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '1.17.x'
    - name: Build
      run: |
        make

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          bin/pam-exec-oauth2
