name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused
    - name: Set up Go 1.16
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.16.x'
    - name: Build
      run: |
        make
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: bin/pam-exec-oauth2
        asset_name: pam-exec-oauth2
        asset_content_type: application/octet-stream